spring.application.name=backend_project
spring.datasource.username=surya
spring.datasource.password=Kondisettisurya
spring.datasource.url=jdbc:mysql://surya.c12qeygsopc4.ap-southeast-2.rds.amazonaws.com:3306/surya
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
